import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { createContext, useContext, useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import Login from "./login";
import UserContext from "./context/userContext";

export default function Home() {
  const router = useRouter();
  const a = useContext(UserContext);

  
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    </div>
  );
}
